# Read the documentation: https://symfony.com/doc/master/bundles/FOSUserBundle/index.html
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "no-reply@wizi.farm"
        sender_name: "Hack Ta Ferme by WiziFarm"
    registration:
        form:
            type: App\Form\RegistrationType
